apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - image: mihirpradhan/website
        imagePullPolicy: Always
        name: website
        ports:
        - containerPort: 80
